name: Pipeline CI/CD Monorepo Innovatech

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Construcción y Push del FRONTEND ---
      - name: Construir imagen Docker - Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-frontend:latest ./Innovatech-frontend

      - name: Subir imagen Docker - Frontend
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-frontend:latest

      # --- Construcción y Push del BACKEND ---
      - name: Construir imagen Docker - Backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-backend:latest ./Innovatech-backend

      - name: Subir imagen Docker - Backend
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-backend:latest

  deploy-to-aws:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Conectarse por SSH a EC2 y desplegar todo el Stack
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Detener y remover contenedores viejos si existen
            sudo docker stop con-frontend con-backend || true
            sudo docker rm con-frontend con-backend || true
            
            # Descargar las versiones más nuevas de las imágenes
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-frontend:latest
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-backend:latest
            
            # Levantar el Backend (en el puerto 5000)
            sudo docker run -d --name con-backend -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-backend:latest
            
            # Levantar el Frontend (en el puerto 80)
            sudo docker run -d --name con-frontend -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-frontend:latest
