name: Pipeline CI/CD Monorepo Innovatech

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3

      - name: Autenticar en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Compilar y subir Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/innovatech-frontend:latest ./Innovatech-frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/innovatech-frontend:latest

      - name: Compilar y subir Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/innovatech-backend:latest ./Innovatech-backend
          docker push ${{ secrets.DOCKER_USERNAME }}/innovatech-backend:latest

  deploy-to-aws:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Ejecutar Despliegue en AWS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # 1. Crear y entrar a una carpeta segura con permisos universales
            mkdir -p /tmp/innovatech-app
            cd /tmp/innovatech-app

            # 2. Iniciar sesión en Docker Hub desde el servidor
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            # 3. Crear la red interna aislada si no existe
            docker network create innovatech-net || true

            # 4. Apagar y eliminar de raíz cualquier contenedor viejo
            docker stop innovatech-front innovatech-back mongo-db || true
            docker rm innovatech-front innovatech-back mongo-db || true

            # 5. Descargar las últimas versiones limpias de las imágenes
            docker pull mongo:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/innovatech-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/innovatech-frontend:latest

            # 6. LEVANTAR EL STACK COMPLETO (Sincronizado y Conectado)
            
            # A) Levantar la Base de Datos privada
            docker run -d --name mongo-db --network innovatech-net -v mongo-data:/data/db mongo:latest
            
            # B) Levantar el Backend inyectándole la URI de MongoDB para que no se caiga
            docker run -d --name innovatech-back --network innovatech-net -p 8080:8080 -e MONGO_URI=mongodb://mongo-db:27017/innovatech ${{ secrets.DOCKER_USERNAME }}/innovatech-backend:latest
            
            # C) Levantar el Frontend en el puerto web estándar
            docker run -d --name innovatech-front --network innovatech-net -p 80:80 ${{ secrets.DOCKER_USERNAME }}/innovatech-frontend:latest